# Generated by Django 3.2 on 2021-05-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('firstname_en', models.CharField(max_length=100, null=True)),
                ('firstname_ar', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('lastname_en', models.CharField(max_length=100, null=True)),
                ('lastname_ar', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('fblink', models.URLField()),
                ('linkedin', models.URLField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberRole', to='users.memberrole')),
                ('role_ar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberRole', to='users.memberrole')),
                ('role_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberRole', to='users.memberrole')),
            ],
        ),
    ]
