# Generated by Django 3.2 on 2021-05-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210513_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_ar',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_en',
        ),
    ]
