# Generated by Django 3.2 on 2021-07-13 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210712_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
