version: "3.3"

services:
  db:
    image: postgres
    env_file:
      - .postgres
    expose:
      - "5432"
  django:
    build:
      context : .
    env_file:
      - .postgres
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: 
      - python manage.py runserver 0.0.0.0:8000
