# Generated by Django 3.2 on 2021-07-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_history_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(null=True)),
                ('body_ar', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
