# Generated by Django 3.1.7 on 2021-04-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HeadsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TopMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('contactinfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Circles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('RMlink', models.URLField()),
                ('headinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headsinfo', to='aboutapi.headsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('logoUrl', models.ImageField(upload_to='')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='aboutapi.events')),
                ('topmembers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topmembers', to='aboutapi.topmembers')),
            ],
        ),
    ]
