# Generated by Django 3.2 on 2021-04-29 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('sessionlink', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HeadsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('firstname_en', models.CharField(max_length=100, null=True)),
                ('firstname_ar', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('lastname_en', models.CharField(max_length=100, null=True)),
                ('lastname_ar', models.CharField(max_length=100, null=True)),
                ('FBlink', models.URLField(blank=True)),
                ('linkedIn', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(null=True)),
                ('body_ar', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='TeamBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('firstname_en', models.CharField(max_length=100, null=True)),
                ('firstname_ar', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('lastname_en', models.CharField(max_length=100, null=True)),
                ('lastname_ar', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('FBlink', models.URLField(blank=True)),
                ('linkedIn', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('firstname_en', models.CharField(max_length=100, null=True)),
                ('firstname_ar', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('lastname_en', models.CharField(max_length=100, null=True)),
                ('lastname_ar', models.CharField(max_length=100, null=True)),
                ('FBlink', models.URLField(blank=True)),
                ('linkedIn', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechCircles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('RMlink', models.URLField()),
                ('designTools', models.TextField()),
                ('designTools_en', models.TextField(null=True)),
                ('designTools_ar', models.TextField(null=True)),
                ('headinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techHeads', to='aboutapi.headsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='NonTechCircles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('skills', models.TextField()),
                ('skills_en', models.TextField(null=True)),
                ('skills_ar', models.TextField(null=True)),
                ('headinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nontechHeads', to='aboutapi.headsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('achievments', models.TextField()),
                ('achievments_en', models.TextField(null=True)),
                ('achievments_ar', models.TextField(null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamboard', to='aboutapi.teamboard')),
                ('board_ar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamboard', to='aboutapi.teamboard')),
                ('board_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamboard', to='aboutapi.teamboard')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('date', models.DateField()),
                ('sessions', models.ManyToManyField(to='aboutapi.EventSessions')),
            ],
        ),
    ]
