# Generated by Django 3.2 on 2021-04-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutteam',
            name='events',
        ),
        migrations.RemoveField(
            model_name='aboutteam',
            name='topmembers',
        ),
    ]
