# Generated by Django 3.2 on 2021-04-16 15:59

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutapi', '0002_auto_20210414_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutteam',
            name='body',
        ),
        migrations.RemoveField(
            model_name='aboutteam',
            name='title',
        ),
        migrations.RemoveField(
            model_name='circles',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='circles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='circles',
            name='title',
        ),
        migrations.RemoveField(
            model_name='events',
            name='description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='title',
        ),
        migrations.RemoveField(
            model_name='headsinfo',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='headsinfo',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='topmembers',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='topmembers',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='topmembers',
            name='photo',
        ),
        migrations.AlterField(
            model_name='topmembers',
            name='contactinfo',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TopMembersTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aboutapi.topmembers')),
            ],
            options={
                'verbose_name': 'top members Translation',
                'db_table': 'aboutapi_topmembers_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='HeadsInfoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aboutapi.headsinfo')),
            ],
            options={
                'verbose_name': 'heads info Translation',
                'db_table': 'aboutapi_headsinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='EventsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aboutapi.events')),
            ],
            options={
                'verbose_name': 'events Translation',
                'db_table': 'aboutapi_events_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='CirclesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('Type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aboutapi.circles')),
            ],
            options={
                'verbose_name': 'circles Translation',
                'db_table': 'aboutapi_circles_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='AboutTeamTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aboutapi.aboutteam')),
            ],
            options={
                'verbose_name': 'about team Translation',
                'db_table': 'aboutapi_aboutteam_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
