# Generated by Django 3.2 on 2021-04-29 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutapi', '0003_auto_20210429_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='sessions',
        ),
        migrations.AddField(
            model_name='events',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventsessions',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eventsessions',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eventsessions',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventsessions',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headsinfo',
            name='firstname_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headsinfo',
            name='firstname_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headsinfo',
            name='lastname_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headsinfo',
            name='lastname_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='achievments_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='achievments_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='board_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamboard', to='aboutapi.teamboard'),
        ),
        migrations.AddField(
            model_name='history',
            name='board_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamboard', to='aboutapi.teamboard'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nontechcircles',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nontechcircles',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nontechcircles',
            name='skills_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nontechcircles',
            name='skills_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nontechcircles',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nontechcircles',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamboard',
            name='firstname_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamboard',
            name='firstname_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamboard',
            name='lastname_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamboard',
            name='lastname_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='techcircles',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='techcircles',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='techcircles',
            name='designTools_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='techcircles',
            name='designTools_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='techcircles',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='techcircles',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topmembers',
            name='firstname_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topmembers',
            name='firstname_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topmembers',
            name='lastname_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topmembers',
            name='lastname_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
