# Generated by Django 3.2 on 2021-04-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutapi', '0004_auto_20210417_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circles',
            options={'verbose_name': 'circle', 'verbose_name_plural': 'circles'},
        ),
        migrations.AlterModelOptions(
            name='circlestranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'circle Translation'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'event Translation'},
        ),
        migrations.AlterModelOptions(
            name='headsinfo',
            options={'verbose_name': 'headInfo', 'verbose_name_plural': 'headsInfo'},
        ),
        migrations.AlterModelOptions(
            name='headsinfotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'headInfo Translation'},
        ),
        migrations.AlterModelOptions(
            name='topmembers',
            options={'verbose_name': 'topMember', 'verbose_name_plural': 'topMembers'},
        ),
        migrations.AlterModelOptions(
            name='topmemberstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'topMember Translation'},
        ),
    ]
